# 03 - Model Training

- Load the processed training and validation datasets
- Separate the features and target variable
- Train different machine learning models
- Evaluate each model on the validation set
- Save the trained models

#### Import libraries

In [3]:
import os
import random
import joblib
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

#### Set the random seed

In [4]:
SEED = 42

random.seed(SEED)
np.random.seed(SEED)

#### Load the processed datasets

In [5]:
train_data = pd.read_csv("../DataSet/processed/telco_churn_train.csv")
validation_data = pd.read_csv("../DataSet/processed/telco_churn_validation.csv")

#### Check the dataset size

In [6]:
print("Training data:", train_data.shape)
print("Validation data:", validation_data.shape)

Training data: (4922, 47)
Validation data: (1055, 47)

#### Preview the training data

In [7]:
train_data.head()

,tenure,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,...,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,SeniorCitizen_0,SeniorCitizen_1,Churn
0,-0.833469,0.444749,-0.607066,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1
1,-0.508058,-1.492135,-0.823672,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0
2,-1.240233,-0.120451,-0.950975,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0
3,0.061411,-0.021293,-0.081500,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0
4,-0.833469,1.166949,-0.495086,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1

#### Separate the features and target

In [8]:
X_train = train_data.drop(columns=["Churn"])
y_train = train_data["Churn"]

X_validation = validation_data.drop(columns=["Churn"])
y_validation = validation_data["Churn"]

#### Check the feature and target shapes

In [9]:
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_validation:", X_validation.shape)
print("y_validation:", y_validation.shape)

X_train: (4922, 46)
y_train: (4922,)
X_validation: (1055, 46)
y_validation: (1055,)

#### Create a function to evaluate each model

In [10]:
def evaluate_model(model_name, model, X, y):
    predictions = model.predict(X)
    probabilities = model.predict_proba(X)[:, 1]

    results = {
        "Model": model_name,
        "Accuracy": accuracy_score(y, predictions),
        "Precision": precision_score(y, predictions),
        "Recall": recall_score(y, predictions),
        "F1-Score": f1_score(y, predictions),
        "ROC-AUC": roc_auc_score(y, probabilities)
    }

    return results

#### Train Logistic Regression

In [11]:
logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=SEED
)

logistic_model.fit(X_train, y_train)

print("Logistic Regression training completed.")

Logistic Regression training completed.

#### Evaluate Logistic Regression

In [12]:
logistic_results = evaluate_model(
    "Logistic Regression",
    logistic_model,
    X_validation,
    y_validation
)

logistic_results

{'Model': 'Logistic Regression',
 'Accuracy': 0.8236966824644549,
 'Precision': 0.6938775510204082,
 'Recall': 0.604982206405694,
 'F1-Score': 0.6463878326996197,
 'ROC-AUC': 0.8532856078788381}

#### Train Decision Tree

In [13]:
decision_tree_model = DecisionTreeClassifier(
    max_depth=5,
    random_state=SEED
)

decision_tree_model.fit(X_train, y_train)

print("Decision Tree training completed.")

Decision Tree training completed.

#### Evaluate Decision Tree

In [14]:
decision_tree_results = evaluate_model(
    "Decision Tree",
    decision_tree_model,
    X_validation,
    y_validation
)

decision_tree_results

{'Model': 'Decision Tree',
 'Accuracy': 0.8,
 'Precision': 0.6458333333333334,
 'Recall': 0.5516014234875445,
 'F1-Score': 0.5950095969289827,
 'ROC-AUC': 0.832689637415285}

#### Train Random Forest

In [15]:
random_forest_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=SEED,
    n_jobs=-1
)

random_forest_model.fit(X_train, y_train)

print("Random Forest training completed.")

Random Forest training completed.

#### Evaluate Random Forest

In [16]:
random_forest_results = evaluate_model(
    "Random Forest",
    random_forest_model,
    X_validation,
    y_validation
)

random_forest_results

{'Model': 'Random Forest',
 'Accuracy': 0.7990521327014218,
 'Precision': 0.6619718309859155,
 'Recall': 0.501779359430605,
 'F1-Score': 0.5708502024291497,
 'ROC-AUC': 0.8429129079422881}

#### Train Multi-Layer Perceptron

In [17]:
mlp_model = MLPClassifier(
    hidden_layer_sizes=(64, 32),
    activation="relu",
    solver="adam",
    max_iter=500,
    early_stopping=True,
    random_state=SEED
)

mlp_model.fit(X_train, y_train)

print("MLP training completed.")

MLP training completed.

#### Evaluate Multi-Layer Perceptron

In [18]:
mlp_results = evaluate_model(
    "Multi-Layer Perceptron",
    mlp_model,
    X_validation,
    y_validation
)

mlp_results

{'Model': 'Multi-Layer Perceptron',
 'Accuracy': 0.804739336492891,
 'Precision': 0.6595744680851063,
 'Recall': 0.5516014234875445,
 'F1-Score': 0.6007751937984496,
 'ROC-AUC': 0.8345356653516879}

#### Compare the validation results

In [19]:
results = pd.DataFrame([
    logistic_results,
    decision_tree_results,
    random_forest_results,
    mlp_results
])

results

                    Model  Accuracy  Precision    Recall  F1-Score   ROC-AUC
0     Logistic Regression  0.823697   0.693878  0.604982  0.646388  0.853286
1           Decision Tree  0.800000   0.645833  0.551601  0.595010  0.832690
2           Random Forest  0.799052   0.661972  0.501779  0.570850  0.842913
3  Multi-Layer Perceptron  0.804739   0.659574  0.551601  0.600775  0.834536

#### Sort the models by ROC-AUC

In [20]:
results.sort_values(
    by="ROC-AUC",
    ascending=False
).reset_index(drop=True)

                    Model  Accuracy  Precision    Recall  F1-Score   ROC-AUC
0     Logistic Regression  0.823697   0.693878  0.604982  0.646388  0.853286
1           Random Forest  0.799052   0.661972  0.501779  0.570850  0.842913
2  Multi-Layer Perceptron  0.804739   0.659574  0.551601  0.600775  0.834536
3           Decision Tree  0.800000   0.645833  0.551601  0.595010  0.832690

#### Save the trained models

In [21]:
os.makedirs("../models", exist_ok=True)

joblib.dump(
    logistic_model,
    "../models/logistic_regression.joblib"
)

joblib.dump(
    decision_tree_model,
    "../models/decision_tree.joblib"
)

joblib.dump(
    random_forest_model,
    "../models/random_forest.joblib"
)

joblib.dump(
    mlp_model,
    "../models/mlp.joblib"
)

print("All trained models saved successfully.")

All trained models saved successfully.

#### Save the validation results

In [22]:
results.to_csv(
    "../models/validation_results.csv",
    index=False
)

print("Validation results saved successfully.")

Validation results saved successfully.

#### Summary

Four classification models were trained and evaluated using the validation set:

- Logistic Regression
- Decision Tree
- Random Forest
- Multi-Layer Perceptron